name:                ansi-monad
version:             0.1.0.0
github:              "tyehle/ansi-monad"
license:             MIT
author:              "Tobin Yehle"
maintainer:          "tobinyehle@gmail.com"
copyright:           "2019 Tobin Yehle"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tyehle/ansi-monad#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal >= 0.9
- colour
- mtl
- containers

library:
  source-dirs: src

executables:
  ansi-monad-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ansi-monad

tests:
  ansi-monad-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ansi-monad
